[package]
name = "jsone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.6", features = ["derive", "wrap_help", "string"] }
globset = "0.4.9"
